# Generated by Django 3.2.15 on 2022-08-18 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('image', models.ImageField(blank='True', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Online_Shoping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('created_by', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
