# Generated by Django 3.2.8 on 2022-09-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
