# Generated by Django 3.2.15 on 2022-09-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0004_rename_text_contact_bag_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='bag_field',
            new_name='highlighted',
        ),
    ]
