# Generated by Django 3.2.15 on 2022-09-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0005_rename_bag_field_contact_highlighted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='highlighted',
            new_name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
