# Generated by Django 3.2.15 on 2022-09-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0006_auto_20220917_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
    ]
