# Generated by Django 3.2.15 on 2022-09-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0009_auto_20220917_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=30),
        ),
    ]
