# Generated by Django 3.2.15 on 2022-09-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0011_alter_contact_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='text',
        ),
    ]
