# Generated by Django 3.2.15 on 2022-09-17 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0013_rename_text_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='selected_items',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
