# Generated by Django 3.2.15 on 2022-09-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0015_alter_contact_selected_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='selected_items',
            field=models.CharField(max_length=100),
        ),
    ]
