# Generated by Django 3.2.15 on 2022-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectstorefront', '0016_alter_contact_selected_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='selected_kgs',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
